trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    echo "SourceBranchName = $(Build.SourceBranchName)"
    echo "SourceBranch = $(Build.SourceBranch)"
    branch_name_extracted=$(echo "${SourceBranch/refs\/head\// }")
  displayName: Extract branch name
  
- task: Docker@2
  inputs:
    containerRegistry: 'hellobedrock_acr'
    repository: 'hellobedrock'
    command: 'buildAndPush'
    Dockerfile: '**/src/Dockerfile'
    tags: 'hello-bedrock-$(Build.SourceBranchName)-$(Build.BuildId)'
  condition: ne(variables['Build.Reason'], 'PullRequest')

- bash: |
    echo "Starting post-task for commit $(Build.SourceVersion) buildId $(Build.BuildId)"
    echo "uuidgen"
    uuidgen
    commitId=$(Build.SourceVersion)
    commitId=$(echo "${commitId:0:7}")
    row_key=$(python -c 'import uuid; print str(uuid.uuid1())')
    row_key=$(echo ${row_key##*-})
    tag_name="hello-bedrock-$(Build.SourceBranchName)-$(Build.BuildId)"
    az storage entity insert --entity PartitionKey=ff55c9d7-4d7e-4072-bd27 RowKey=$row_key commitId=$(Build.SourceVersion) p1=$(Build.BuildId) imageTag=$tag_name --table-name deployments --account-name saakhtacjteststorage --account-key $ACCOUNT_KEY
  displayName: Set Container Journey variables in database
  env:
    ACCOUNT_KEY: $(ACCOUNT_KEY)
