trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    echo "SourceBranchName = $(Build.SourceBranchName)"
    echo "SourceBranch = $(Build.SourceBranch)"
    branch_name_extracted=$(echo "${SourceBranch/refs\/head\//}")
    echo '##vso[task.setvariable variable=branchname]$branch_name_extracted'
    echo "Setting branchname to $branch_name_extracted"
    echo '##vso[task.setvariable variable=sauce]crushed tomatoes'
    echo "Setting sauce to $sauce"
  displayName: Extract branch name

- bash: |
    echo my pipeline variable is $(sauce)
    echo my other variable is $(branchname)
  displayName: Test

- task: Docker@2
  inputs:
    containerRegistry: 'diamondrings_acr'
    repository: 'diamondrings'
    command: 'buildAndPush'
    Dockerfile: '**/src/Dockerfile'
    tags: 'diamond-rings-$(BRANCH_NAME)-$(Build.BuildId)'
  condition: ne(variables['Build.Reason'], 'PullRequest')

