trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: Docker@2
  inputs:
    containerRegistry: 'diamondrings_acr'
    repository: 'diamondrings'
    command: 'buildAndPush'
    Dockerfile: '**/src/Dockerfile'
    tags: 'diamond-rings-$(Build.SourceBranchName)-$(Build.BuildId)'
  condition: ne(variables['Build.Reason'], 'PullRequest')
