trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    echo "SourceBranchName = $(Build.SourceBranchName)"
    echo "SourceBranch = $(Build.SourceBranch)"
    branch_name_extracted=$(echo "${SourceBranch/refs\/head\// }")
    echo "##vso[task.setvariable variable=BRANCH_NAME;]$branch_name_extracted"
  displayName: Extract branch name
  
- task: Docker@2
  inputs:
    containerRegistry: 'diamondrings_acr'
    repository: 'diamondrings'
    command: 'buildAndPush'
    Dockerfile: '**/src/Dockerfile'
    tags: 'diamond-rings-$branch_name_extracted-$(Build.BuildId)'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  env:
    BRANCH_NAME: $(BRANCH_NAME)
